CREATE TABLE IF NOT EXISTS core (
    id INTEGER PRIMARY KEY,
    scryfall_id TEXT UNIQUE NOT NULL,
    arena_id INTEGER,
    mtgo_id INTEGER,
    mtgo_foil_id INTEGER,
    layout TEXT NOT NULL,
    oracle_id TEXT,
    rulings_uri TEXT,
    scryfall_uri TEXT,  -- Link to scryfall page for the card.
    uri TEXT,  -- Link to download the card object from scryfall api.
    all_parts BOOLEAN NOT NULL, -- If true, corresponding entries in all_parts table.
    card_faces BOOLEAN NOT NULL,  -- If true, corresponding entries in card_faces table.
    cmc REAL NOT NULL,
    defense TEXT,
    game_changer BOOLEAN,
    hand_modifier TEXT,
    -- Format legalities (legal, not_legal, restricted, banned) --
    standard TEXT NOT NULL,
    future TEXT NOT NULL,
    historic TEXT NOT NULL,
    timeless TEXT NOT NULL,
    gladiator TEXT NOT NULL,
    pioneer TEXT NOT NULL,
    explorer TEXT NOT NULL,
    modern TEXT NOT NULL,
    legacy TEXT NOT NULL,
    pauper TEXT NOT NULL,
    vintage TEXT NOT NULL,
    penny TEXT NOT NULL,
    commander TEXT NOT NULL,
    oathbreaker TEXT NOT NULL,
    standardbrawl TEXT NOT NULL,
    brawl TEXT NOT NULL,
    alchemy TEXT NOT NULL,
    paupercommander TEXT NOT NULL,
    duel TEXT NOT NULL,
    oldschool TEXT NOT NULL,
    premodern TEXT NOT NULL,
    predh TEXT NOT NULL,
    -- end Format legalities --
    life_modifier TEXT,
    loyalty TEXT,
    mana_cost TEXT,
    name NOT NULL,
    oracle_text TEXT,
    power TEXT,
    reserved BOOLEAN NOT NULL,
    toughness TEXT,
    type_line TEXT NOT NULL,
    artist TEXT,
    booster BOOLEAN NOT NULL,
    border_color TEXT NOT NULL,
    card_back_id TEXT NOT NULL,
    collector_number TEXT NOT NULL,
    content_warning BOOLEAN, -- True if you should avoid using this print.
    digital BOOLEAN NOT NULL,
    -- Finishes --
    foil BOOLEAN NOT NULL,
    nonfoil BOOLEAN NOT NULL,
    etched BOOLEAN NOT NULL,
    -- end Finishes --
    flavor_name TEXT,  -- e.g. Godzilla card names
    flavor_text TEXT,
    frame TEXT NOT NULL,
    full_art BOOLEAN,
    -- Available in --
    paper BOOLEAN NOT NULL,
    arena BOOLEAN NOT NULL,
    mtgo BOOLEAN NOT NULL,
    -- End Available --
    highres_image BOOLEAN NOT NULL,
    illustration_id TEXT,
    image_status TEXT,
    -- Image uris --
    png TEXT,
    border_crop TEXT,
    art_crop TEXT,
    large TEXT,
    normal TEXT,
    small TEXT,
    -- end Image URIS --
    oversized BOOLEAN NOT NULL,
    -- Prices --
    price_usd TEXT,
    price_usd_foil TEXT,
    price_usd_etched TEXT,
    price_eur TEXT,
    price_eur_foil TEXT,
    price_eur_etched TEXT,
    price_tix TEXT,
    -- end Prices --
    printed_name TEXT,
    printed_text TEXT,
    printed_type_line TEXT,
    promo BOOLEAN,
    rarity TEXT NOT NULL,
    released_at TEXT NOT NULL,
    reprint BOOLEAN NOT NULL,
    scryfall_set_uri TEXT NOT NULL,
    set_name TEXT NOT NULL,  -- Full set name
    set_search_uri TEXT NOT NULL,  -- Link to set on Scryfall
    set_type TEXT NOT NULL,  -- (e.g. expansion)
    set_uri TEXT NOT NULL,  -- link to card's set object on Scryfall API.
    set_code TEXT NOT NULL,
    set_id TEXT NOT NULL,  -- Set object UUID
    story_spotlight BOOLEAN NOT NULL,
    textless BOOLEAN NOT NULL,
    variation BOOLEAN NOT NULL,
    variation_of TEXT,  -- printing id of printing this card is a variation of.
    security_stamp TEXT,
    watermark TEXT
);


CREATE TABLE IF NOT EXISTS all_parts (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    scryfall_id TEXT NOT NULL,  -- Scryfall id for this card
    component TEXT NOT NULL,  -- What role this card plays in the relationship (e.g. token)
    name TEXT NOT NULL,
    type_line TEXT NOT NULL,
    uri TEXT NOT NULL,  -- URI for card object
    FOREIGN KEY(core_id) REFERENCES core(id)
);


CREATE TABLE IF NOT EXISTS card_faces (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    artist_id TEXT,
    cmc REAL,
    color_indicator TEXT,
    colors TEXT,
    defense TEXT,
    flavor_text TEXT,
    illustration_id TEXT,
    -- Image URIS --
    png TEXT,
    border_crop TEXT,
    art_crop TEXT,
    large TEXT,
    normal TEXT,
    small TEXT,
    -- end Image URIS --
    layout TEXT,
    loyalty TEXT,
    mana_cost TEXT NOT NULL,
    name TEXT NOT NULL,
    oracle_id TEXT,
    oracle_text TEXT,
    power TEXT,
    printed_name TEXT,  -- Localized name
    printed_text TEXT,  -- Localized text
    printed_type_line TEXT,  -- Localized type line
    toughness TEXT,
    type_line TEXT,
    watermark TEXT,
    FOREIGN KEY(core_id) REFERENCES core(id)
);

-- Multiverse IDs --
CREATE TABLE IF NOT EXISTS multiverse_ids (
    id INTEGER PRIMARY KEY,
    multiverse_id INTEGER UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS card_multiverse_relationships (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    multiverse_id INTEGER NOT NULL,
    FOREIGN KEY(core_id) REFERENCES core(id),
    FOREIGN KEY(multiverse_id) REFERENCES multiverse_ids(id)
);
-- Multiverse IDs --

-- Colors --
CREATE TABLE IF NOT EXISTS colors (
    id INTEGER PRIMARY KEY,
    color_name TEXT NOT NULL,
    color_code TEXT NOT NULL
);

INSERT INTO colors (color_name, color_code) VALUES
    ('White', 'W'),
    ('Blue', 'U'),
    ('Black', 'B'),
    ('Red', 'R'),
    ('Green', 'G'),
    ('Colorless', 'C');
-- Colors --

-- Color Relationships --
CREATE TABLE IF NOT EXISTS card_color_relationships (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    color_id INTEGER NOT NULL,
    relationship_type TEXT NOT NULL CHECK (
        relationship_type IN ('colors', 'color_identity', 'color_indicator',
                              'produced_mana')
    ),
    FOREIGN KEY(core_id) REFERENCES core(id),
    FOREIGN KEY(color_id) REFERENCES colors(id)
);
-- Color Relationships --

-- Keywords --
CREATE TABLE IF NOT EXISTS keywords (
    id INTEGER PRIMARY KEY,
    keyword_name TEXT NOT NULL
);

INSERT INTO keywords (keyword_name) VALUES
    ('Deathtouch'),
    ('Defender'),
    ('Double Strike'),
    ('Enchant'),
    ('Equip'),
    ('First Strike'),
    ('Flash'),
    ('Flying'),
    ('Haste'),
    ('Hexproof'),
    ('Indestructible'),
    ('Intimidate'),
    ('Landwalk'),
    ('Lifelink'),
    ('Protection'),
    ('Reach'),
    ('Shroud'),
    ('Trample'),
    ('Vigilance'),
    ('Ward'),
    ('Banding'),
    ('Rampage'),
    ('Cumulative Upkeep'),
    ('Flanking'),
    ('Phasing'),
    ('Buyback'),
    ('Shadow'),
    ('Cycling'),
    ('Echo'),
    ('Horsemanship'),
    ('Fading'),
    ('Kicker'),
    ('Flashback'),
    ('Madness'),
    ('Fear'),
    ('Morph'),
    ('Amplify'),
    ('Provoke'),
    ('Storm'),
    ('Affinity'),
    ('Entwine'),
    ('Modular'),
    ('Sunburst'),
    ('Bushido'),
    ('Soulshift'),
    ('Splice'),
    ('Offering'),
    ('Ninjutsu'),
    ('Epic'),
    ('Convoke'),
    ('Dredge'),
    ('Transmute'),
    ('Bloodthirst'),
    ('Haunt'),
    ('Replicate'),
    ('Forecast'),
    ('Graft'),
    ('Recover'),
    ('Ripple'),
    ('Split Second'),
    ('Suspend'),
    ('Vanishing'),
    ('Absorb'),
    ('Aura Swap'),
    ('Delve'),
    ('Fortify'),
    ('Frenzy'),
    ('Gravestorm'),
    ('Poisonous'),
    ('Transfigure'),
    ('Champion'),
    ('Changeling'),
    ('Evoke'),
    ('Hideaway'),
    ('Prowl'),
    ('Reinforce'),
    ('Conspire'),
    ('Persist'),
    ('Wither'),
    ('Retrace'),
    ('Devour'),
    ('Exalted'),
    ('Unearth'),
    ('Cascade'),
    ('Annihilator'),
    ('Level Up'),
    ('Rebound'),
    ('Umbra Armor'),
    ('Infect'),
    ('Battle Cry'),
    ('Living Weapon'),
    ('Undying'),
    ('Miracle'),
    ('Soulbond'),
    ('Overload'),
    ('Scavenge'),
    ('Unleash'),
    ('Cipher'),
    ('Evolve'),
    ('Extort'),
    ('Fuse'),
    ('Bestow'),
    ('Tribute'),
    ('Dethrone'),
    ('Hidden Agenda'),
    ('Outlast'),
    ('Prowess'),
    ('Dash'),
    ('Exploit'),
    ('Menace'),
    ('Renown'),
    ('Awaken'),
    ('Devoid'),
    ('Ingest'),
    ('Myriad'),
    ('Surge'),
    ('Skulk'),
    ('Emerge'),
    ('Escalate'),
    ('Melee'),
    ('Crew'),
    ('Fabricate'),
    ('Partner'),
    ('Undaunted'),
    ('Improvise'),
    ('Aftermath'),
    ('Embalm'),
    ('Eternalize'),
    ('Afflict'),
    ('Ascend'),
    ('Assist'),
    ('Jump-Start'),
    ('Mentor'),
    ('Afterlife'),
    ('Riot'),
    ('Spectacle'),
    ('Escape'),
    ('Companion'),
    ('Mutate'),
    ('Encore'),
    ('Boast'),
    ('Foretell'),
    ('Demonstrate'),
    ('Daybound'),
    ('Nightbound'),
    ('Disturb'),
    ('Decayed'),
    ('Cleave'),
    ('Training'),
    ('Compleated'),
    ('Reconfigure'),
    ('Blitz'),
    ('Casualty'),
    ('Enlist'),
    ('Read Ahead'),
    ('Ravenous'),
    ('Squad'),
    ('Space Sculptor'),
    ('Visit'),
    ('Prototype'),
    ('Living Metal'),
    ('More Than Meets the Eye'),
    ('For Mirrodin!'),
    ('Toxic'),
    ('Backup'),
    ('Bargain'),
    ('Craft'),
    ('Disguise'),
    ('Solved'),
    ('Plot'),
    ('Saddle'),
    ('Spree'),
    ('Freerunning'),
    ('Gift'),
    ('Offspring'),
    ('Impending');

CREATE TABLE IF NOT EXISTS card_keywords (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    keyword_id INTEGER NOT NULL,
    UNIQUE(core_id, keyword_id),
    FOREIGN KEY(core_id) REFERENCES core(id),
    FOREIGN KEY(keyword_id) REFERENCES keywords(id)
);
-- Keywords --

-- Card Types --
CREATE TABLE IF NOT EXISTS card_types (
    id INTEGER PRIMARY KEY,
    type_name TEXT UNIQUE NOT NULL,
    type_category TEXT NOT NULL CHECK (type_category IN ('super', 'base', 'sub'))
);

INSERT INTO card_types (type_name, type_category) VALUES
    -- Super --
    ('Basic', 'super'),
    ('Legendary', 'super'),
    ('Ongoing', 'super'),
    ('Snow', 'super'),
    ('World', 'super'),
    -- Super --

    -- Base --
    ('Artifact', 'base'),
    ('Battle', 'base'),
    ('Conspiracy', 'base'),
    ('Creature', 'base'),
    ('Dungeon', 'base'),
    ('Enchantment', 'base'),
    ('Instant', 'base'),
    ('Kindred', 'base'),
    ('Land', 'base'),
    ('Phenomenon', 'base'),
    ('Plane', 'base'),
    ('Planeswalker', 'base'),
    ('Scheme', 'base'),
    ('Sorcery', 'base'),
    ('Vanguard', 'base'),
    -- Base --

    -- Sub Types --
    -- https://mtg.wiki/page/Subtype
    -- 205.3r Phenomenon cards, scheme cards, vanguard cards,
    -- and conspiracy cards have no subtypes. --

    -- Artifact --
    ('Attraction', 'sub'),
    ('Blood', 'sub'),
    ('Bobblehead', 'sub'),
    ('Clue', 'sub'),
    ('Contraption', 'sub'),
    ('Equipment', 'sub'),
    ('Food', 'sub'),
    ('Fortification', 'sub'),
    ('Gold', 'sub'),
    ('Incubator', 'sub'),
    ('Junk', 'sub'),
    ('Lander', 'sub'),
    ('Map', 'sub'),
    ('Powerstone', 'sub'),
    ('Spacecraft', 'sub'),
    ('Treasure', 'sub'),
    ('Vehicle', 'sub'),
    -- Artifact --

    -- Battle --
    ('Siege', 'sub'),
    -- Battle --

    -- Creature --
    -- Eternal --
    ('Advisor', 'sub'),
    ('Aetherborn', 'sub'),
    ('Alien', 'sub'),
    ('Ally', 'sub'),
    ('Angel', 'sub'),
    ('Antelope', 'sub'),
    ('Ape', 'sub'),
    ('Archer', 'sub'),
    ('Archon', 'sub'),
    ('Armadillo', 'sub'),
    ('Army', 'sub'),
    ('Artificer', 'sub'),
    ('Assassin', 'sub'),
    ('Assembly-Worker', 'sub'),
    ('Astartes', 'sub'),
    ('Atog', 'sub'),
    ('Aurochs', 'sub'),
    ('Avatar', 'sub'),
    ('Azra', 'sub'),
    ('Badger', 'sub'),
    ('Balloon', 'sub'),
    ('Barbarian', 'sub'),
    ('Bard', 'sub'),
    ('Basilisk', 'sub'),
    ('Bat', 'sub'),
    ('Bear', 'sub'),
    ('Beast', 'sub'),
    ('Beaver', 'sub'),
    ('Beeble', 'sub'),
    ('Beholder', 'sub'),
    ('Berserker', 'sub'),
    ('Bird', 'sub'),
    ('Blinkmoth', 'sub'),
    ('Boar', 'sub'),
    ('Bringer', 'sub'),
    ('Brushwagg', 'sub'),
    ('Camarid', 'sub'),
    ('Camel', 'sub'),
    ('Capybara', 'sub'),
    ('Caribou', 'sub'),
    ('Carrier', 'sub'),
    ('Cat', 'sub'),
    ('Centaur', 'sub'),
    ('Child', 'sub'),
    ('Chimera', 'sub'),
    ('Citizen', 'sub'),
    ('Cleric', 'sub'),
    ('Clown', 'sub'),
    ('Cockatrice', 'sub'),
    ('Construct', 'sub'),
    ('Coward', 'sub'),
    ('Coyote', 'sub'),
    ('Crab', 'sub'),
    ('Crocodile', 'sub'),
    ('Ctan', 'sub'),
    ('Custodes', 'sub'),
    ('Cyberman', 'sub'),
    ('Cyclops', 'sub'),
    ('Dalek', 'sub'),
    ('Dauthi', 'sub'),
    ('Demigod', 'sub'),
    ('Demon', 'sub'),
    ('Deserter', 'sub'),
    ('Detective', 'sub'),
    ('Devil', 'sub'),
    ('Dinosaur', 'sub'),
    ('Djinn', 'sub'),
    ('Doctor', 'sub'),
    ('Dog', 'sub'),
    ('Dragon', 'sub'),
    ('Drake', 'sub'),
    ('Dreadnought', 'sub'),
    ('Drone', 'sub'),
    ('Druid', 'sub'),
    ('Dryad', 'sub'),
    ('Dwarf', 'sub'),
    ('Efreet', 'sub'),
    ('Egg', 'sub'),
    ('Elder', 'sub'),
    ('Eldrazi', 'sub'),
    ('Elemental', 'sub'),
    ('Elephant', 'sub'),
    ('Elf', 'sub'),
    ('Elk', 'sub'),
    ('Employee', 'sub'),
    ('Eye', 'sub'),
    ('Faerie', 'sub'),
    ('Ferret', 'sub'),
    ('Fish', 'sub'),
    ('Flagbearer', 'sub'),
    ('Fox', 'sub'),
    ('Fractal', 'sub'),
    ('Frog', 'sub'),
    ('Fungus', 'sub'),
    ('Gamer', 'sub'),
    ('Gargoyle', 'sub'),
    ('Germ', 'sub'),
    ('Giant', 'sub'),
    ('Gith', 'sub'),
    ('Glimmer', 'sub'),
    ('Gnoll', 'sub'),
    ('Gnome', 'sub'),
    ('Goat', 'sub'),
    ('Goblin', 'sub'),
    ('God', 'sub'),
    ('Golem', 'sub'),
    ('Gorgon', 'sub'),
    ('Graveborn', 'sub'),
    ('Gremlin', 'sub'),
    ('Griffin', 'sub'),
    ('Guest', 'sub'),
    ('Hag', 'sub'),
    ('Halfling', 'sub'),
    ('Hamster', 'sub'),
    ('Harpy', 'sub'),
    ('Hellion', 'sub'),
    ('Hippo', 'sub'),
    ('Hippogriff', 'sub'),
    ('Homarid', 'sub'),
    ('Homunculus', 'sub'),
    ('Horror', 'sub'),
    ('Horse', 'sub'),
    ('Human', 'sub'),
    ('Hydra', 'sub'),
    ('Hyena', 'sub'),
    ('Illusion', 'sub'),
    ('Imp', 'sub'),
    ('Incarnation', 'sub'),
    ('Inkling', 'sub'),
    ('Inquisitor', 'sub'),
    ('Insect', 'sub'),
    ('Jackal', 'sub'),
    ('Jellyfish', 'sub'),
    ('Juggernaut', 'sub'),
    ('Kavu', 'sub'),
    ('Kirin', 'sub'),
    ('Kithkin', 'sub'),
    ('Knight', 'sub'),
    ('Kobold', 'sub'),
    ('Kor', 'sub'),
    ('Kraken', 'sub'),
    ('Llama', 'sub'),
    ('Lamia', 'sub'),
    ('Lammasu', 'sub'),
    ('Leech', 'sub'),
    ('Leviathan', 'sub'),
    ('Lhurgoyf', 'sub'),
    ('Licid', 'sub'),
    ('Lizard', 'sub'),
    ('Manticore', 'sub'),
    ('Masticore', 'sub'),
    ('Mercenary', 'sub'),
    ('Merfolk', 'sub'),
    ('Metathran', 'sub'),
    ('Minion', 'sub'),
    ('Minotaur', 'sub'),
    ('Mite', 'sub'),
    ('Mole', 'sub'),
    ('Monger', 'sub'),
    ('Mongoose', 'sub'),
    ('Monk', 'sub'),
    ('Monkey', 'sub'),
    ('Moonfolk', 'sub'),
    ('Mount', 'sub'),
    ('Mouse', 'sub'),
    ('Mutant', 'sub'),
    ('Myr', 'sub'),
    ('Mystic', 'sub'),
    ('Nautilus', 'sub'),
    ('Necron', 'sub'),
    ('Nephilim', 'sub'),
    ('Nightmare', 'sub'),
    ('Nightstalker', 'sub'),
    ('Ninja', 'sub'),
    ('Noble', 'sub'),
    ('Noggle', 'sub'),
    ('Nomad', 'sub'),
    ('Nymph', 'sub'),
    ('Octopus', 'sub'),
    ('Ogre', 'sub'),
    ('Ooze', 'sub'),
    ('Orb', 'sub'),
    ('Orc', 'sub'),
    ('Orgg', 'sub'),
    ('Otter', 'sub'),
    ('Ouphe', 'sub'),
    ('Ox', 'sub'),
    ('Oyster', 'sub'),
    ('Pangolin', 'sub'),
    ('Peasant', 'sub'),
    ('Pegasus', 'sub'),
    ('Pentavite', 'sub'),
    ('Performer', 'sub'),
    ('Pest', 'sub'),
    ('Phelddagrif', 'sub'),
    ('Phoenix', 'sub'),
    ('Phyrexian', 'sub'),
    ('Pilot', 'sub'),
    ('Pincher', 'sub'),
    ('Pirate', 'sub'),
    ('Plant', 'sub'),
    ('Porcupine', 'sub'),
    ('Possum', 'sub'),
    ('Praetor', 'sub'),
    ('Primarch', 'sub'),
    ('Prism', 'sub'),
    ('Processor', 'sub'),
    ('Rabbit', 'sub'),
    ('Raccoon', 'sub'),
    ('Ranger', 'sub'),
    ('Rat', 'sub'),
    ('Rebel', 'sub'),
    ('Reflection', 'sub'),
    ('Rhino', 'sub'),
    ('Rigger', 'sub'),
    ('Robot', 'sub'),
    ('Rogue', 'sub'),
    ('Sable', 'sub'),
    ('Salamander', 'sub'),
    ('Samurai', 'sub'),
    ('Sand', 'sub'),
    ('Saproling', 'sub'),
    ('Satyr', 'sub'),
    ('Scarecrow', 'sub'),
    ('Scientist', 'sub'),
    ('Scion', 'sub'),
    ('Scorpion', 'sub'),
    ('Scout', 'sub'),
    ('Sculpture', 'sub'),
    ('Serf', 'sub'),
    ('Serpent', 'sub'),
    ('Servo', 'sub'),
    ('Shade', 'sub'),
    ('Shaman', 'sub'),
    ('Shapeshifter', 'sub'),
    ('Shark', 'sub'),
    ('Sheep', 'sub'),
    ('Siren', 'sub'),
    ('Skeleton', 'sub'),
    ('Skunk', 'sub'),
    ('Slith', 'sub'),
    ('Sliver', 'sub'),
    ('Sloth', 'sub'),
    ('Slug', 'sub'),
    ('Snail', 'sub'),
    ('Snake', 'sub'),
    ('Soldier', 'sub'),
    ('Soltari', 'sub'),
    ('Spawn', 'sub'),
    ('Specter', 'sub'),
    ('Spellshaper', 'sub'),
    ('Sphinx', 'sub'),
    ('Spider', 'sub'),
    ('Spike', 'sub'),
    ('Spirit', 'sub'),
    ('Splinter', 'sub'),
    ('Sponge', 'sub'),
    ('Squid', 'sub'),
    ('Squirrel', 'sub'),
    ('Starfish', 'sub'),
    ('Surrakar', 'sub'),
    ('Survivor', 'sub'),
    ('Synth', 'sub'),
    ('Tentacle', 'sub'),
    ('Tetravite', 'sub'),
    ('Thalakos', 'sub'),
    ('Thopter', 'sub'),
    ('Thrull', 'sub'),
    ('Tiefling', 'sub'),
    ('Time Lord', 'sub'),
    ('Toy', 'sub'),
    ('Treefolk', 'sub'),
    ('Trilobite', 'sub'),
    ('Triskelavite', 'sub'),
    ('Troll', 'sub'),
    ('Turtle', 'sub'),
    ('Tyranid', 'sub'),
    ('Unicorn', 'sub'),
    ('Vampire', 'sub'),
    ('Varmint', 'sub'),
    ('Vedalken', 'sub'),
    ('Volver', 'sub'),
    ('Wall', 'sub'),
    ('Walrus', 'sub'),
    ('Warlock', 'sub'),
    ('Warrior', 'sub'),
    ('Weasel', 'sub'),
    ('Weird', 'sub'),
    ('Werewolf', 'sub'),
    ('Whale', 'sub'),
    ('Wizard', 'sub'),
    ('Wolf', 'sub'),
    ('Wolverine', 'sub'),
    ('Wombat', 'sub'),
    ('Worm', 'sub'),
    ('Wraith', 'sub'),
    ('Wurm', 'sub'),
    ('Yeti', 'sub'),
    ('Zombie', 'sub'),
    ('Zubera', 'sub'),
    -- Eternal --
    -- Non Eternal (These types may no longer be in use) --
    ('Alicorn', 'sub'),
    ('Armored', 'sub'),
    ('Art', 'sub'),
    ('Artist', 'sub'),
    ('Athlete', 'sub'),
    ('Attendee', 'sub'),
    ('Autobot', 'sub'),
    ('Aven', 'sub'),
    ('Boxer', 'sub'),
    ('Brainiac', 'sub'),
    ('Bureaucrat', 'sub'),
    ('Chameleon', 'sub'),
    ('Champion', 'sub'),
    ('Chef', 'sub'),
    ('Chicken', 'sub'),
    ('Clamfolk', 'sub'),
    ('Cobbler', 'sub'),
    ('Cow', 'sub'),
    ('Cyborg', 'sub'),
    ('Deer', 'sub'),
    ('Designer', 'sub'),
    ('Die', 'sub'),
    ('Donkey', 'sub'),
    ('Elemental?', 'sub'),
    ('Elves', 'sub'),
    ('Expansion Symbol', 'sub'),
    ('Fighter', 'sub'),
    ('Glass', 'sub'),
    ('Gorilla', 'sub'),
    ('Grandchild', 'sub'),
    ('Gus', 'sub'),
    ('Hatificer', 'sub'),
    ('Half', 'sub'),
    ('Head', 'sub'),
    ('Hero', 'sub'),
    ('Judge', 'sub'),
    ('Kangaroo', 'sub'),
    ('Killbot', 'sub'),
    ('Lady of Proper Etiquette', 'sub'),
    ('Lobster', 'sub'),
    ('Locus', 'sub'),
    ('Mammoth', 'sub'),
    ('Mime', 'sub'),
    ('Mummy', 'sub'),
    ('Paratrooper', 'sub'),
    ('Penguin', 'sub'),
    ('Pony', 'sub'),
    ('Present', 'sub'),
    ('Reveler', 'sub'),
    ('Ship', 'sub'),
    ('Shoemaker', 'sub'),
    ('Sketch', 'sub'),
    ('Spuzzem', 'sub'),
    ('Spy', 'sub'),
    ('Stained', 'sub'),
    ('Teddy', 'sub'),
    ('Townsfolk', 'sub'),
    ('The Biggest Baddest Nastiest Scariest Creature Youll Ever See', 'sub'),
    ('Tree', 'sub'),
    ('Vampyre', 'sub'),
    ('Villain', 'sub'),
    ('Wainwright', 'sub'),
    ('Waiter', 'sub'),
    ('Windmill', 'sub'),
    ('Wrestler', 'sub'),
    ('Zonian', 'sub'),
    -- Non Eternal --
    -- Creature --

    -- Enchantment --
    ('Aura', 'sub'),
    ('Background', 'sub'),
    ('Cartouche', 'sub'),
    ('Case', 'sub'),
    ('Class', 'sub'),
    ('Curse', 'sub'),
    ('Role', 'sub'),
    ('Room', 'sub'),
    ('Rune', 'sub'),
    ('Saga', 'sub'),
    ('Shard', 'sub'),
    ('Shrine', 'sub'),
    -- Enchantment --

    -- Land --
    -- Basic --
    ('Plains', 'sub'),
    ('Island', 'sub'),
    ('Swamp', 'sub'),
    ('Mountain', 'sub'),
    ('Forest', 'sub'),
    -- Basic --
    -- Non-basic --
    ('Cave', 'sub'),
    ('Desert', 'sub'),
    ('Gate', 'sub'),
    ('Lair', 'sub'),
    ('Locus', 'sub'),
    ('Mine', 'sub'),
    ('Planet', 'sub'),
    ('Power-Plant', 'sub'),
    ('Sphere', 'sub'),
    ('Tower', 'sub'),
    ('Town', 'sub'),
    ('Urzas', 'sub'),
    -- Non-basic --
    -- Land --

    -- Plane --
    ('The Abyss', 'sub'),
    ('Alara', 'sub'),
    ('Amonkhet', 'sub'),
    ('Antausia', 'sub'),
    ('Arcavios', 'sub'),
    ('Arkhos', 'sub'),
    ('Azgol', 'sub'),
    ('Belenon', 'sub'),
    ('Bolass Meditation Realm', 'sub'),
    ('Capenna', 'sub'),
    ('Cridhe', 'sub'),
    ('Dominaria', 'sub'),
    ('Echoir', 'sub'),
    ('Eldraine', 'sub'),
    ('Equilor', 'sub'),
    ('Ergamon', 'sub'),
    ('Fabacin', 'sub'),
    ('Fiora', 'sub'),
    ('Gargantikar', 'sub'),
    ('Gobakhan', 'sub'),
    ('Ikoria', 'sub'),
    ('Innistrad', 'sub'),
    ('Iquatana', 'sub'),
    ('Ir', 'sub'),
    ('Ixalan', 'sub'),
    ('Kaladesh', 'sub'),
    ('Kaldheim', 'sub'),
    ('Kamigawa', 'sub'),
    ('Karsus', 'sub'),
    ('Kephalai', 'sub'),
    ('Kinshala', 'sub'),
    ('Kolbahan', 'sub'),
    ('Kylem', 'sub'),
    ('Kyneth', 'sub'),
    ('Lorwyn', 'sub'),
    ('Luvion', 'sub'),
    ('Mercadia', 'sub'),
    ('Mirrodin', 'sub'),
    ('Moag', 'sub'),
    ('Mongseng', 'sub'),
    ('Muraganda', 'sub'),
    ('New Phyrexia', 'sub'),
    ('Phyrexia', 'sub'),
    ('Pyrulea', 'sub'),
    ('Rabiah', 'sub'),
    ('Rath', 'sub'),
    ('Ravnica', 'sub'),
    ('Regatha', 'sub'),
    ('Segovia', 'sub'),
    ('Serras Realm', 'sub'),
    ('Shadowmoor', 'sub'),
    ('Shandalar', 'sub'),
    ('Shenmeng', 'sub'),
    ('Tarkir', 'sub'),
    ('Theros', 'sub'),
    ('Ulgrotha', 'sub'),
    ('Valla', 'sub'),
    ('Vryn', 'sub'),
    ('Wildfire', 'sub'),
    ('Xerex', 'sub'),
    ('Zendikar', 'sub'),
    ('Zhalfir', 'sub'),

    -- UB --
    ('Alfava Metraxis', 'sub'),
    ('Androzani Minor', 'sub'),
    ('Apalapucia', 'sub'),
    ('Darillium', 'sub'),
    ('Earth', 'sub'),
    ('Gallifrey', 'sub'),
    ('Horsehead Nebula', 'sub'),
    ('Kandoka', 'sub'),
    ('Mars', 'sub'),
    ('Moon', 'sub'),
    ('Necros', 'sub'),
    ('New Earth', 'sub'),
    ('Outside Mutters Spiral', 'sub'),
    ('Skaro', 'sub'),
    ('Spacecraft', 'sub'),
    ('The Dalek Asylum', 'sub'),
    ('The Library', 'sub'),
    ('Time', 'sub'),
    ('Trenzalore', 'sub'),
    ('Unknown Planet', 'sub'),
    -- UB --
    -- Plane --

    -- Planeswalker --
    -- https://mtg.wiki/page/Planeswalker_type --
    ('Ajani', 'sub'),
    ('Aminatou', 'sub'),
    ('Angrath', 'sub'),
    ('Arlinn', 'sub'),
    ('Ashiok', 'sub'),
    ('Bahamut', 'sub'),
    ('Basri', 'sub'),
    ('Bolas', 'sub'),
    ('Calix', 'sub'),
    ('Chandra', 'sub'),
    ('Comet', 'sub'),
    ('Dack', 'sub'),
    ('Dakkon', 'sub'),
    ('Daretti', 'sub'),
    ('Davriel', 'sub'),
    ('Dihada', 'sub'),
    ('Domri', 'sub'),
    ('Dovin', 'sub'),
    ('Ellywick', 'sub'),
    ('Elminster', 'sub'),
    ('Elspeth', 'sub'),
    ('Estrid', 'sub'),
    ('Freyalise', 'sub'),
    ('Garruk', 'sub'),
    ('Gideon', 'sub'),
    ('Grist', 'sub'),
    ('Guff', 'sub'),
    ('Huatli', 'sub'),
    ('Jace', 'sub'),
    ('Jared', 'sub'),
    ('Jaya', 'sub'),
    ('Jeska', 'sub'),
    ('Kaito', 'sub'),
    ('Karn', 'sub'),
    ('Kasmina', 'sub'),
    ('Kaya', 'sub'),
    ('Kiora', 'sub'),
    ('Koth', 'sub'),
    ('Liliana', 'sub'),
    ('Lolth', 'sub'),
    ('Lukka', 'sub'),
    ('Minsc', 'sub'),
    ('Mordenkainen', 'sub'),
    ('Nahiri', 'sub'),
    ('Narset', 'sub'),
    ('Niko', 'sub'),
    ('Nissa', 'sub'),
    ('Nixilis', 'sub'),
    ('Oko', 'sub'),
    ('Quintorius', 'sub'),
    ('Ral', 'sub'),
    ('Rowan', 'sub'),
    ('Saheeli', 'sub'),
    ('Samut', 'sub'),
    ('Sarkhan', 'sub'),
    ('Serra', 'sub'),
    ('Sivitri', 'sub'),
    ('Sorin', 'sub'),
    ('Szat', 'sub'),
    ('Tamiyo', 'sub'),
    ('Tasha', 'sub'),
    ('Teferi', 'sub'),
    ('Teyo', 'sub'),
    ('Tezzeret', 'sub'),
    ('Tibalt', 'sub'),
    ('Tyvar', 'sub'),
    ('Ugin', 'sub'),
    ('Urza', 'sub'),
    ('Venser', 'sub'),
    ('Vivien', 'sub'),
    ('Vraska', 'sub'),
    ('Vronos', 'sub'),
    ('Will', 'sub'),
    ('Windgrace', 'sub'),
    ('Wrenn', 'sub'),
    ('Xenagos', 'sub'),
    ('Yanggu', 'sub'),
    ('Yanling', 'sub'),
    ('Zariel', 'sub'),
    -- Plansewalker --

    -- Spell --
    ('Adventure', 'sub'),
    ('Arcane', 'sub'),
    ('Chorus', 'sub'),
    ('Lesson', 'sub'),
    ('Trap', 'sub'),
    -- Spell --

    -- Dungeon --
    ('Undercity', 'sub')
    -- Dungeon --
    -- Sub Types --
;

CREATE TABLE IF NOT EXISTS card_type_relationships (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    type_id INTEGER NOT NULL,
    FOREIGN KEY(core_id) REFERENCES core(id),
    FOREIGN KEY(type_id) REFERENCES card_types(id)
);
-- Card Types --

-- Artist --
CREATE TABLE IF NOT EXISTS artists (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    scryfall_id TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS card_artist_relationships (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    artist_id INTEGER NOT NULL,
    FOREIGN KEY(core_id) REFERENCES core(id),
    FOREIGN KEY(artist_id) REFERENCES artist(id)
);
-- Artist --

-- Attraction lights --
CREATE TABLE IF NOT EXISTS card_attraction_lights (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    light_number INTEGER NOT NULL CHECK (light_number IN (2, 3, 4, 5, 6)),
    FOREIGN KEY(core_id) REFERENCES core(id)
);
-- Attraction lights --

-- Frame effects --
CREATE TABLE IF NOT EXISTS frame_effects (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL CHECK (
        name IN ('legendary', 'miracle', 'enchantment', 'draft', 'devoid',
                 'tombstone', 'colorshifted', 'inverted', 'sunmoondfc',
                 'compasslanddfc', 'originpwdfc', 'mooneldrazidfc',
                 'waxingandwaningmoondfc', 'showcase', 'extendedart',
                 'companion', 'etched', 'snow', 'lesson', 'shatteredglass',
                 'convertdfc', 'fandfc', 'upsidedowndfc', 'spree')
    )
);

INSERT INTO frame_effects (name) VALUES
    ('legendary'),
    ('miracle'),
    ('enchantment'),
    ('draft'),
    ('devoid'),
    ('tombstone'),
    ('colorshifted'),
    ('inverted'),
    ('sunmoondfc'),
    ('compasslanddfc'),
    ('originpwdfc'),
    ('mooneldrazidfc'),
    ('waxingandwaningmoondfc'),
    ('showcase'),
    ('extendedart'),
    ('companion'),
    ('etched'),
    ('snow'),
    ('lesson'),
    ('shatteredglass'),
    ('convertdfc'),
    ('fandfc'),
    ('upsidedowndfc'),
    ('spree')
);

CREATE TABLE IF NOT EXISTS card_frame_effects (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    effect_id INTEGER NOT NULL,
    FOREIGN KEY(core_id) REFERENCES core(id),
    FOREIGN KEY(effect_id) REFERENCES frame_effects(id)
);
-- Frame effects --

-- Promo --
CREATE TABLE IF NOT EXISTS promo_types (
    id INTEGER PRIMARY KEY,
    name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS card_promo_type_relationships (
    id INTEGER PRIMARY KEY,
    core_id INTEGER NOT NULL,
    promo_type_id INTEGER NOT NULL,
    FOREIGN KEY(core_id) REFERENCES core(id),
    FOREIGN KEY(promo_type_id) REFERENCES promo_types(id)
);
-- Promo --
